[colors.cursor]
cursor = "0xff2600"
text = "0xf1c1c1"

[colors.primary]
background = "0x191919"
foreground = "0xeaeaea"

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[shell]
args = ["-u"]
program = "/usr/bin/tmux"
